"""Library-scoped persistence and authorization services."""

from dithyramba.provenance import (
    BlobRecord,
    CollectionMembershipRecord,
    CoverageReportRecord,
    IngestBatchResult,
    IngestDisposition,
    IngestInputOutcome,
    OmissionRecord,
    PersistedSourceOutcome,
    ProcessingRunRecord,
    ProcessingRunStatus,
    SourceFamilyRole,
    SourceFragmentRecord,
    SourceRecord,
    SourceVersionRecord,
    TerminalInputOutcome,
)

from .answer_projection import SQLiteAnswerProjectionRepository
from .errors import (
    AccessPolicyNotFoundError,
    AnswerProjectionNotFoundError,
    AnswerProjectionPersistenceError,
    AuthorizationError,
    BackupError,
    CollectionNotFoundError,
    CorpusSnapshotNotFoundError,
    CoverageReportNotFoundError,
    EvidencePacketNotFoundError,
    LibraryNotFoundError,
    OutboxExportError,
    PersistenceConflictError,
    PersistenceError,
    PersistenceIntegrityError,
    ProcessingRunNotFoundError,
    QueryRequestNotFoundError,
    RecallArtifactNotFoundError,
    ResearchSessionNotFoundError,
    ResearchSessionPersistenceError,
    SessionArtifactNotFoundError,
    SourceNotFoundError,
    SourceVersionNotFoundError,
)
from .meaning import SQLiteMeaningRepository
from .models import (
    AccessPolicyRecord,
    AuthorizedRead,
    BackupRecord,
    CollectionRecord,
    LibraryRecord,
    OutboxEvent,
    OutboxExportResult,
    SourceFragmentText,
)
from .reasoning import SQLiteReasoningRepository
from .recall import SQLiteRecallBackend
from .relations import SQLiteRelationRepository
from .repository import (
    LibraryRepository,
    initialize_library,
    library_logical_identity_hash,
    list_libraries,
    open_library,
)
from .sessions import SQLiteResearchSessionRepository
from .structure import SQLiteStructureRepository

__all__ = [
    "AccessPolicyNotFoundError",
    "AccessPolicyRecord",
    "AnswerProjectionNotFoundError",
    "AnswerProjectionPersistenceError",
    "AuthorizationError",
    "AuthorizedRead",
    "BackupError",
    "BackupRecord",
    "BlobRecord",
    "CollectionMembershipRecord",
    "CollectionNotFoundError",
    "CollectionRecord",
    "CorpusSnapshotNotFoundError",
    "CoverageReportNotFoundError",
    "CoverageReportRecord",
    "EvidencePacketNotFoundError",
    "IngestBatchResult",
    "IngestDisposition",
    "IngestInputOutcome",
    "LibraryNotFoundError",
    "LibraryRecord",
    "LibraryRepository",
    "OmissionRecord",
    "OutboxEvent",
    "OutboxExportError",
    "OutboxExportResult",
    "PersistedSourceOutcome",
    "PersistenceConflictError",
    "PersistenceError",
    "PersistenceIntegrityError",
    "ProcessingRunNotFoundError",
    "ProcessingRunRecord",
    "ProcessingRunStatus",
    "QueryRequestNotFoundError",
    "RecallArtifactNotFoundError",
    "ResearchSessionNotFoundError",
    "ResearchSessionPersistenceError",
    "SQLiteAnswerProjectionRepository",
    "SQLiteMeaningRepository",
    "SQLiteReasoningRepository",
    "SQLiteRecallBackend",
    "SQLiteRelationRepository",
    "SQLiteResearchSessionRepository",
    "SQLiteStructureRepository",
    "SessionArtifactNotFoundError",
    "SourceFamilyRole",
    "SourceFragmentRecord",
    "SourceFragmentText",
    "SourceNotFoundError",
    "SourceRecord",
    "SourceVersionNotFoundError",
    "SourceVersionRecord",
    "TerminalInputOutcome",
    "initialize_library",
    "library_logical_identity_hash",
    "list_libraries",
    "open_library",
]
